main:
  push:
    - stages:
        - name: sync to github
          imports: https://cnb.cool/pylover/key/-/blob/main/github.yml
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/pylover7/PyTool.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}

"(main|dev/*)":
  pull_request:
    - name: AI 代码审评
      stages:
      - name: 代码评审
        image: cnbcool/ai-review:latest
        settings:
          type: code-review
    - name: TCA 后端代码审查
      stages:
      - image: tencentcom/tca-plugin:latest
        settings:
          mode: local
          org_sid: DlV3t9YzRYP
          team_name: pytool
          scheme_id: 7844
          scan_dir: backend/app
        settingsFrom:
          - https://cnb.cool/pylover/key/-/blob/main/tca.yml
    - name: TCA 前端代码分析
      stages:
      - image: tencentcom/tca-plugin:latest
        settings:
          mode: local
          org_sid: DlV3t9YzRYP
          team_name: pytool
          scheme_id: 7845
          scan_dir: frontend/src
        settingsFrom:
          - https://cnb.cool/pylover/key/-/blob/main/tca.yml

$:
  vscode:
    - docker:
        image: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:env
        volumes:
            - ./backend/.venv:rw
            - ./backend/static:rw
            - ./frontend/node_modules:rw
            - ./docs/node_modules:rw
      runner:
        cpus: 8
      services:
        - vscode
        - docker
      stages:
        - name: ls
          script: ls -la

  web_trigger_one:
    - services:
        - docker
      env:
        IMAGE_TAG: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:env
      stages:
        - name: docker build
          script: docker build -t ${IMAGE_TAG} . -f .ide/Dockerfile
        - name: docker list
          script: docker images
        - name: docker push
          script: docker push ${IMAGE_TAG}  
