"""add_security_features

Revision ID: 1e99a7fcad44
Revises: 
Create Date: 2026-05-23 04:12:13.233109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1e99a7fcad44'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roleapilink', schema=None) as batch_op:
        batch_op.drop_constraint('fk_roleapilink_role_id_role', type_='foreignkey')
        batch_op.drop_constraint('fk_roleapilink_api_id_api', type_='foreignkey')
        batch_op.create_foreign_key('fk_roleapilink_role_id_role', 'role', ['role_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_roleapilink_api_id_api', 'api', ['api_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('rolemenulink', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rolemenulink_role_id_role', type_='foreignkey')
        batch_op.drop_constraint('fk_rolemenulink_menu_id_menu', type_='foreignkey')
        batch_op.create_foreign_key('fk_rolemenulink_role_id_role', 'role', ['role_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_rolemenulink_menu_id_menu', 'menu', ['menu_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('password_history', sa.JSON(), nullable=True))

    with op.batch_alter_table('userrolelink', schema=None) as batch_op:
        batch_op.drop_constraint('fk_userrolelink_role_id_role', type_='foreignkey')
        batch_op.drop_constraint('fk_userrolelink_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_userrolelink_role_id_role', 'role', ['role_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_userrolelink_user_id_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userrolelink', schema=None) as batch_op:
        batch_op.drop_constraint('fk_userrolelink_role_id_role', type_='foreignkey')
        batch_op.drop_constraint('fk_userrolelink_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_userrolelink_role_id_role', 'role', ['role_id'], ['id'])
        batch_op.create_foreign_key('fk_userrolelink_user_id_user', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_history')
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_count')

    with op.batch_alter_table('rolemenulink', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rolemenulink_role_id_role', type_='foreignkey')
        batch_op.drop_constraint('fk_rolemenulink_menu_id_menu', type_='foreignkey')
        batch_op.create_foreign_key('fk_rolemenulink_role_id_role', 'role', ['role_id'], ['id'])
        batch_op.create_foreign_key('fk_rolemenulink_menu_id_menu', 'menu', ['menu_id'], ['id'])

    with op.batch_alter_table('roleapilink', schema=None) as batch_op:
        batch_op.drop_constraint('fk_roleapilink_role_id_role', type_='foreignkey')
        batch_op.drop_constraint('fk_roleapilink_api_id_api', type_='foreignkey')
        batch_op.create_foreign_key('fk_roleapilink_role_id_role', 'role', ['role_id'], ['id'])
        batch_op.create_foreign_key('fk_roleapilink_api_id_api', 'api', ['api_id'], ['id'])

    # ### end Alembic commands ###
