"""initial_create_all_tables

Revision ID: 582670eaa9ea
Revises: 
Create Date: 2026-06-04 19:27:41.203157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '582670eaa9ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('method', sa.Enum('GET', 'POST', 'PUT', 'DELETE', 'PATCH', name='methodtype'), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api'))
    )
    op.create_table('department',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('parentId', sa.Uuid(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('principal', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_department')),
    sa.UniqueConstraint('name', name=op.f('uq_department_name'))
    )
    op.create_table('emailconfig',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('host', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('sender', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('use_tls', sa.Boolean(), nullable=False),
    sa.Column('use_ssl', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emailconfig'))
    )
    op.create_table('iprule',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ip_cidr', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('rule_type', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_iprule'))
    )
    op.create_table('loginlog',
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('browser', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('behavior', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loginlog'))
    )
    with op.batch_alter_table('loginlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loginlog_ip'), ['ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_loginlog_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_loginlog_time'), ['time'], unique=False)
        batch_op.create_index(batch_op.f('ix_loginlog_username'), ['username'], unique=False)

    op.create_table('menu',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parentId', sa.Uuid(), nullable=True),
    sa.Column('menuType', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('component', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('redirect', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('extraIcon', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('transitionName', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('enterTransition', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('leaveTransition', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('dynamicLevel', sa.Integer(), nullable=False),
    sa.Column('activePath', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('auths', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('frameSrc', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('frameLoading', sa.Boolean(), nullable=False),
    sa.Column('keepAlive', sa.Boolean(), nullable=False),
    sa.Column('hiddenTag', sa.Boolean(), nullable=False),
    sa.Column('fixedTag', sa.Boolean(), nullable=False),
    sa.Column('showLink', sa.Boolean(), nullable=False),
    sa.Column('showParent', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu'))
    )
    op.create_table('oauthconfig',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('qq_app_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('qq_app_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('qq_redirect_uri', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('qq_enabled', sa.Boolean(), nullable=False),
    sa.Column('wechat_app_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('wechat_app_secret', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('wechat_redirect_uri', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('wechat_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauthconfig'))
    )
    op.create_table('operationlog',
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operationlog'))
    )
    with op.batch_alter_table('operationlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operationlog_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_operationlog_time'), ['time'], unique=False)
        batch_op.create_index(batch_op.f('ix_operationlog_username'), ['username'], unique=False)

    op.create_table('role',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role')),
    sa.UniqueConstraint('code', name=op.f('uq_role_code')),
    sa.UniqueConstraint('name', name=op.f('uq_role_name'))
    )
    op.create_table('securitypolicy',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('min_password_length', sa.Integer(), nullable=False),
    sa.Column('require_uppercase', sa.Boolean(), nullable=False),
    sa.Column('require_lowercase', sa.Boolean(), nullable=False),
    sa.Column('require_digit', sa.Boolean(), nullable=False),
    sa.Column('require_special', sa.Boolean(), nullable=False),
    sa.Column('password_history_count', sa.Integer(), nullable=False),
    sa.Column('max_login_attempts', sa.Integer(), nullable=False),
    sa.Column('lockout_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('captcha_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_securitypolicy'))
    )
    op.create_table('siteconfig',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('site_desc', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('logo', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('default_lang', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('enable_email', sa.Boolean(), nullable=False),
    sa.Column('copyright', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('icp', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_siteconfig'))
    )
    op.create_table('systemlog',
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_systemlog'))
    )
    with op.batch_alter_table('systemlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_systemlog_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_systemlog_time'), ['time'], unique=False)

    op.create_table('roleapilink',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('api_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['api.id'], name=op.f('fk_roleapilink_api_id_api'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_roleapilink_role_id_role'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'api_id', name=op.f('pk_roleapilink'))
    )
    op.create_table('rolemenulink',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('menu_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], name=op.f('fk_rolemenulink_menu_id_menu'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_rolemenulink_role_id_role'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'menu_id', name=op.f('pk_rolemenulink'))
    )
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('sex', sa.Integer(), nullable=False),
    sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('qq_openid', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('qq_unionid', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('qq_nickname', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('qq_avatar', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_history', sa.JSON(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_user_department_id_department')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('phone', name=op.f('uq_user_phone')),
    sa.UniqueConstraint('qq_openid', name=op.f('uq_user_qq_openid')),
    sa.UniqueConstraint('qq_unionid', name=op.f('uq_user_qq_unionid')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_status'), ['status'], unique=False)

    op.create_table('file',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('extension', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('uploader_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['uploader_id'], ['user.id'], name=op.f('fk_file_uploader_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file'))
    )
    op.create_table('notice',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], name=op.f('fk_notice_creator_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notice'))
    )
    op.create_table('userrolelink',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_userrolelink_role_id_role'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_userrolelink_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_userrolelink'))
    )
    op.create_table('noticeread',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('notice_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['notice_id'], ['notice.id'], name=op.f('fk_noticeread_notice_id_notice')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_noticeread_user_id_user')),
    sa.PrimaryKeyConstraint('id', 'notice_id', 'user_id', name=op.f('pk_noticeread'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('noticeread')
    op.drop_table('userrolelink')
    op.drop_table('notice')
    op.drop_table('file')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_status'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_department_id'))

    op.drop_table('user')
    op.drop_table('rolemenulink')
    op.drop_table('roleapilink')
    with op.batch_alter_table('systemlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_systemlog_time'))
        batch_op.drop_index(batch_op.f('ix_systemlog_level'))

    op.drop_table('systemlog')
    op.drop_table('siteconfig')
    op.drop_table('securitypolicy')
    op.drop_table('role')
    with op.batch_alter_table('operationlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operationlog_username'))
        batch_op.drop_index(batch_op.f('ix_operationlog_time'))
        batch_op.drop_index(batch_op.f('ix_operationlog_level'))

    op.drop_table('operationlog')
    op.drop_table('oauthconfig')
    op.drop_table('menu')
    with op.batch_alter_table('loginlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loginlog_username'))
        batch_op.drop_index(batch_op.f('ix_loginlog_time'))
        batch_op.drop_index(batch_op.f('ix_loginlog_level'))
        batch_op.drop_index(batch_op.f('ix_loginlog_ip'))

    op.drop_table('loginlog')
    op.drop_table('iprule')
    op.drop_table('emailconfig')
    op.drop_table('department')
    op.drop_table('api')
    # ### end Alembic commands ###
