"""initial tables

Revision ID: ec209d42800e
Revises: 
Create Date: 2026-05-16 16:17:58.818441

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec209d42800e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('parentId', sa.Uuid(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('principal', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('loginlog',
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('browser', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('behavior', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loginlog_ip'), 'loginlog', ['ip'], unique=False)
    op.create_index(op.f('ix_loginlog_level'), 'loginlog', ['level'], unique=False)
    op.create_index(op.f('ix_loginlog_time'), 'loginlog', ['time'], unique=False)
    op.create_index(op.f('ix_loginlog_username'), 'loginlog', ['username'], unique=False)
    op.create_table('menu',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parentId', sa.Uuid(), nullable=True),
    sa.Column('menuType', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('component', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('redirect', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('extraIcon', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('transitionName', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('enterTransition', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('leaveTransition', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('dynamicLevel', sa.Integer(), nullable=False),
    sa.Column('activePath', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('auths', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('frameSrc', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('frameLoading', sa.Boolean(), nullable=False),
    sa.Column('keepAlive', sa.Boolean(), nullable=False),
    sa.Column('hiddenTag', sa.Boolean(), nullable=False),
    sa.Column('fixedTag', sa.Boolean(), nullable=False),
    sa.Column('showLink', sa.Boolean(), nullable=False),
    sa.Column('showParent', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operationlog',
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operationlog_level'), 'operationlog', ['level'], unique=False)
    op.create_index(op.f('ix_operationlog_time'), 'operationlog', ['time'], unique=False)
    op.create_index(op.f('ix_operationlog_username'), 'operationlog', ['username'], unique=False)
    op.create_table('role',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('systemlog',
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_systemlog_level'), 'systemlog', ['level'], unique=False)
    op.create_index(op.f('ix_systemlog_time'), 'systemlog', ['time'], unique=False)
    op.create_table('roleapilink',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('api_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['api.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'api_id')
    )
    op.create_table('rolemenulink',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('menu_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'menu_id')
    )
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('sex', sa.Integer(), nullable=False),
    sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('qq_openid', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('qq_unionid', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('qq_nickname', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('qq_avatar', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('qq_openid'),
    sa.UniqueConstraint('qq_unionid'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_department_id'), 'user', ['department_id'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_status'), 'user', ['status'], unique=False)
    op.create_table('notice',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userrolelink',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('noticeread',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('notice_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['notice_id'], ['notice.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'notice_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('noticeread')
    op.drop_table('userrolelink')
    op.drop_table('notice')
    op.drop_index(op.f('ix_user_status'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_department_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('rolemenulink')
    op.drop_table('roleapilink')
    op.drop_index(op.f('ix_systemlog_time'), table_name='systemlog')
    op.drop_index(op.f('ix_systemlog_level'), table_name='systemlog')
    op.drop_table('systemlog')
    op.drop_table('role')
    op.drop_index(op.f('ix_operationlog_username'), table_name='operationlog')
    op.drop_index(op.f('ix_operationlog_time'), table_name='operationlog')
    op.drop_index(op.f('ix_operationlog_level'), table_name='operationlog')
    op.drop_table('operationlog')
    op.drop_table('menu')
    op.drop_index(op.f('ix_loginlog_username'), table_name='loginlog')
    op.drop_index(op.f('ix_loginlog_time'), table_name='loginlog')
    op.drop_index(op.f('ix_loginlog_level'), table_name='loginlog')
    op.drop_index(op.f('ix_loginlog_ip'), table_name='loginlog')
    op.drop_table('loginlog')
    op.drop_table('department')
    op.drop_table('api')
    # ### end Alembic commands ###
